# Generated by Django 3.2 on 2021-09-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0002_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
